 
name: Docker build and test

on: push

jobs:
  build:
   runs-on: ubuntu-latest
  
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t sparse_mkl .
     - name: Run tests inside the container
       run: docker run -v $PWD:/app sparse_mkl python3 -m pytest tests/test.py --runslow
